### ISSUE TITLE
step2 error

### ISSUE THREAD

**Issue by LeeYEAH2** [yangli557/AnnoSINE#12]
Dear developer:
I met such error below: 
AnnoSINE_v2 -t 10 -a 2 --num_alignments 50000 -rpm 0 --copy_number 3 --shift 100 -auto 1 3 genome.fa ./
Example: AnnoSINE_v2 3 ../Input_Files/test.fasta ../Output_Files
Please input the path of genomic sequence
************************************************************************
*************************** AnnoSINE START! ****************************
************************************************************************
====== Step 1: HMMER prediction and structure search has begun =======
Step1_process_hmm not finished! Will regenerate the result!

Step 1 mode-3::hmm_predict uses  36.732131242752075  s
process_hmm_output_3:read_genome_assembly uses 0.002218484878540039
Processing the hmm prediction ...
process_hmm_output_3:process_hmm_output_2_r1 uses 0.03598666191101074
Processing the hmm prediction ...
process_hmm_output_3:process_hmm_output_2_r2 uses 0.01045846939086914
Processing the hmm prediction ...
process_hmm_output_3:process_hmm_output_2_r3 uses 0.010227441787719727
process_hmm_output_3:merge_same_hmm_output uses 6.103515625e-05
process_hmm_output_3:for_loop uses 2.002716064453125e-05
Step 1 mode-3::process_hmm_output_3 uses  0.061069488525390625  s
Step1_sine_part not finished! Will regenerate the result!
Step 1 mode-3::sine_finder uses  2.8167171478271484  s
Step 1 mode-3::process_sine_finder uses  0.002566814422607422  s
Step1_merge_part not finished! Will regenerate the result!
Step 1::merge_tsd_input uses  0.0011138916015625  s
Step 1 totally uses  39.61408591270447  s

======================== Step 1 has been done ========================

================ Step 2: TSD identification has begun ================
Step2_search_tsd not finished! Will regenerate the result!
Successfully split the file into 1 chunks, with a maximum of 1000 lines per chunk.
/Share/user/liyilou/miniconda3/envs/EDTA2/lib/python3.10/site-packages/AnnoSINE/TSD_Searcher_multi.js:138
const FNA_PATTERN = new RegExp(FNA_HEAD_PATTERN + FNA_SEQUENCE_PATTERN, "g");
                    ^

SyntaxError: Invalid regular expression: /(?<head>>[^
]*
)(?<sequence>[atcgATCGNnXx
]+)/: Invalid group
    at RegExp (native)
    at Object.<anonymous> (/Share/user/liyilou/miniconda3/envs/EDTA2/lib/python3.10/site-packages/AnnoSINE/TSD_Searcher_multi.js:138:21)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
Traceback (most recent call last):
  File "/Share/user/liyilou/miniconda3/envs/EDTA2/bin/AnnoSINE_v2", line 10, in <module>
    sys.exit(main())
  File "/Share/user/liyilou/miniconda3/envs/EDTA2/lib/python3.10/site-packages/AnnoSINE/AnnoSINE_v2.py", line 1707, in main
    search_tsd(output_genome_assembly_path, script_dir,cpus)
  File "/Share/user/liyilou/miniconda3/envs/EDTA2/lib/python3.10/site-packages/AnnoSINE/AnnoSINE_v2.py", line 544, in search_tsd
    f=open(s,'r')
FileNotFoundError: [Errno 2] No such file or directory: './/TSD_output_chunk_1.fa'

Do you have any idea what's wrong with this?

**Comment by LeeYEAH2** [comment]
#6  as mentioned in issue 6，I upgraded my nodejs version & problems solved for HPC users whose libso.6 doesn't support newest version of nodejs, I recommend using node v12.22.12 which I installed and tested successfully
