### ISSUE TITLE
SyntaxError: Invalid regular expression: /(?<head>>[^

### ISSUE THREAD

**Issue by jordana-olive** [yangli557/AnnoSINE#6]
Hi there!
I'm trying to run AnnoSINE, but always I have same error, as above. I tried to use other sequences for testing. 
The running command is in the /bin folder. Can anyone shed a light on it? Thankss

Error:

======================== Step 1 has been done ========================

================ Step 2: TSD identification has begun ================
/home/eniac/jordana/AnnoSINE/bin/TSD_Searcher.js:133
const FNA_PATTERN = new RegExp(FNA_HEAD_PATTERN + FNA_SEQUENCE_PATTERN, "g");
                    ^

SyntaxError: Invalid regular expression: /(?<head>>[^
]*
)(?<sequence>[atcgATCG
]+)/: Invalid group
    at new RegExp (<anonymous>)
    at Object.<anonymous> (/home/eniac/jordana/AnnoSINE/bin/TSD_Searcher.js:133:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Traceback (most recent call last):
  File "AnnoSINE.py", line 1174, in <module>
    main_function()
  File "AnnoSINE.py", line 1125, in main_function
    process_tsd_output(input_genome_assembly_path, output_genome_assembly_path)
  File "AnnoSINE.py", line 301, in process_tsd_output
    with open(filename) as f2:
FileNotFoundError: [Errno 2] No such file or directory: '../Testing/output/Step2_tsd.txt'

**Comment by jordana-olive** [comment]
I solved it! Apparently it was my node version. I updated it and it works.
